server:
  port: 8021
spring:
  #����Ŀ��������
  application:
    name: rabbitmq-provider
  #����rabbitMq ������
  rabbitmq:
    host: 192.168.1.173
    port: 5672
    username: guest
    password: guest
    publisher-returns: true
  publisher-confirms: true